# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f96d7136a6d4dd93b083a85e08ec9221"
name = "shopcomponentdev2"
handle = "shopcomponentdev2"
application_url = "https://settled-climbing-condor.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"
  include_fields=["id","admin_graphql_api_id","app_id","browser_ip","buyer_accepts_marketing","cancel_reason","cancelled_at","cart_token","checkout_id","checkout_token","client_details","closed_at","company","confirmation_number","confirmed","created_at","currency","current_shipping_price_set","current_subtotal_price","current_subtotal_price_set","current_total_additional_fees_set","current_total_discounts", "current_total_discounts_set","current_total_duties_set","current_total_price","current_total_price_set", "current_total_tax", "current_total_tax_set","customer_locale", "discount_codes","duties_included", "estimated_taxes","financial_status","fulfillment_status","landing_site","landing_site_ref","location_id","merchant_business_entity_id","merchant_of_record_app_id","name","note","note_attributes","number","order_number","payment_gateway_names","po_number","presentment_currency","processed_at","reference","referring_site","source_identifier","source_name","source_url","subtotal_price","subtotal_price_set","tags","tax_exempt","tax_lines","taxes_included","test","token","total_discounts","total_discounts_set","total_line_items_price","total_line_items_price_set","total_outstanding","total_price","total_price_set","total_shipping_price_set","total_tax","total_tax_set","total_tip_received","total_weight","updated_at","user_id","discount_applications","fulfillments","payment_terms","refunds","returns"]
  filter = "id:* AND app_id:279364894721"


  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/update"
  include_fields=["id","admin_graphql_api_id","app_id","browser_ip","buyer_accepts_marketing","cancel_reason","cancelled_at","cart_token","checkout_id","checkout_token","client_details","closed_at","company","confirmation_number","confirmed","created_at","currency","current_shipping_price_set","current_subtotal_price","current_subtotal_price_set","current_total_additional_fees_set","current_total_discounts", "current_total_discounts_set","current_total_duties_set","current_total_price","current_total_price_set", "current_total_tax", "current_total_tax_set","customer_locale", "discount_codes","duties_included", "estimated_taxes","financial_status","fulfillment_status","landing_site","landing_site_ref","location_id","merchant_business_entity_id","merchant_of_record_app_id","name","note","note_attributes","number","order_number","payment_gateway_names","po_number","presentment_currency","processed_at","reference","referring_site","source_identifier","source_name","source_url","subtotal_price","subtotal_price_set","tags","tax_exempt","tax_lines","taxes_included","test","token","total_discounts","total_discounts_set","total_line_items_price","total_line_items_price_set","total_outstanding","total_price","total_price_set","total_shipping_price_set","total_tax","total_tax_set","total_tip_received","total_weight","updated_at","user_id","discount_applications","fulfillments","payment_terms","refunds","returns"]
  
  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"
  

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,unauthenticated_read_checkouts,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_products"

[auth]
redirect_urls = ["https://settled-climbing-condor.ngrok-free.app/auth/callback", "https://settled-climbing-condor.ngrok-free.app/auth/shopify/callback", "https://settled-climbing-condor.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
